graph 
%% T((Taxon)) -- scientificName --> TN((TaxonName))
TN((TaxonName)) -- isBasedOn --> S(CreativeWork)
S(CreativeWork) -- creator --> P((Person))
P((Person)) -- address --> PO(PostalAddress)
P((Person)) -- affiliation --> O(Organisation)
P((Person)) -- alumniOf --> O(Organization)
O(Organization) -- funder --> P((Person))